//
//  LocalizedStrings.swift
//  Taroter
//
//  Created by Jakub Dąbrowski on 14/10/2021.
//

import Foundation

struct LocalizedStrings {
    // MARK: - Main View
    public static let welcomeTitle = NSLocalizedString("welcome_title", comment: "")
    public static let welcomeButton = NSLocalizedString("welcome_button", comment: "")
    
    // 1st screen
    public static let firstTitle = NSLocalizedString("first_title", comment: "")
    public static let firstDescription = NSLocalizedString("first_description", comment: "")
    
    // 2nd screen
    public static let secondTitle = NSLocalizedString("second_title", comment: "")
    public static let secondDescription = NSLocalizedString("second_description", comment: "")
    
    // 3rd screen
    public static let thirdTitle = NSLocalizedString("third_title", comment: "")
    public static let thirdDescription = NSLocalizedString("third_description", comment: "")
    
    // 4th screen
    public static let fourthTitle = NSLocalizedString("fourth_title", comment: "")
    public static let fourthDescription = NSLocalizedString("fourth_description", comment: "")
    
    // MARK: - YES/NO/MAYBE
    public static let yes = NSLocalizedString("yes", comment: "")
    public static let no = NSLocalizedString("no", comment: "")
    public static let maybe = NSLocalizedString("maybe", comment: "")
    
    // MARK: - Arcana
    public static let majorArcana = NSLocalizedString("major_arcana", comment: "")
    public static let minorArcana = NSLocalizedString("minor_arcana", comment: "")
    
    // MARK: - Cards View
    public static let search = NSLocalizedString("search", comment: "")
    public static let arcana = NSLocalizedString("arcana", comment: "")
    public static let yesOrNo = NSLocalizedString("yes_or_no", comment: "")
    public static let keywords = NSLocalizedString("keywords", comment: "")
    public static let uprightKeywords = NSLocalizedString("upright_keywords", comment: "")
    public static let reversedKeywords = NSLocalizedString("reversed_keywords", comment: "")
    public static let cards = NSLocalizedString("cards", comment: "")
    
    // MARK: - Cards
    // - Major Arcana -
    public static let fool = NSLocalizedString("fool", comment: "")
    public static let magician = NSLocalizedString("magician", comment: "")
    public static let highPriestess = NSLocalizedString("high_priestess", comment: "")
    public static let empress = NSLocalizedString("empress", comment: "")
    public static let emperor = NSLocalizedString("emperor", comment: "")
    public static let hierophant = NSLocalizedString("hierophant", comment: "")
    public static let lovers = NSLocalizedString("lovers", comment: "")
    public static let chariot = NSLocalizedString("chariot", comment: "")
    public static let strength = NSLocalizedString("strength", comment: "")
    public static let hermit = NSLocalizedString("hermit", comment: "")
    public static let wheelOfFortune = NSLocalizedString("wheel_of_fortune", comment: "")
    public static let justice = NSLocalizedString("justice", comment: "")
    public static let hangedMan = NSLocalizedString("hanged_man", comment: "")
    public static let death = NSLocalizedString("death", comment: "")
    public static let temperance = NSLocalizedString("temperance", comment: "")
    public static let devil = NSLocalizedString("devil", comment: "")
    public static let tower = NSLocalizedString("tower", comment: "")
    public static let star = NSLocalizedString("star", comment: "")
    public static let moon = NSLocalizedString("moon", comment: "")
    public static let sun = NSLocalizedString("sun", comment: "")
    public static let judgement = NSLocalizedString("judgement", comment: "")
    public static let world = NSLocalizedString("world", comment: "")

    // - Minor Arcana -
    // Wands
    public static let aceOfWands = NSLocalizedString("ace_of_wands", comment: "")
    public static let twoOfWands = NSLocalizedString("two_of_wands", comment: "")
    public static let threeOfWands = NSLocalizedString("three_of_wands", comment: "")
    public static let fourOfWands = NSLocalizedString("four_of_wands", comment: "")
    public static let fiveOfWands = NSLocalizedString("five_of_wands", comment: "")
    public static let sixOfWands = NSLocalizedString("six_of_wands", comment: "")
    public static let sevenOfWands = NSLocalizedString("seven_of_wands", comment: "")
    public static let eightOfWands = NSLocalizedString("eight_of_wands", comment: "")
    public static let nineOfWands = NSLocalizedString("nine_of_wands", comment: "")
    public static let tenOfWands = NSLocalizedString("ten_of_wands", comment: "")
    public static let pageOfWands = NSLocalizedString("page_of_wands", comment: "")
    public static let knightOfWands = NSLocalizedString("knight_of_wands", comment: "")
    public static let queenOfWands = NSLocalizedString("queen_of_wands", comment: "")
    public static let kingOfWands = NSLocalizedString("king_of_wands", comment: "")

    // Pentacles
    public static let aceOfPentacles = NSLocalizedString("ace_of_pentacles", comment: "")
    public static let twoOfPentacles = NSLocalizedString("two_of_pentacles", comment: "")
    public static let threeOfPentacles = NSLocalizedString("three_of_pentacles", comment: "")
    public static let fourOfPentacles = NSLocalizedString("four_of_pentacles", comment: "")
    public static let fiveOfPentacles = NSLocalizedString("five_of_pentacles", comment: "")
    public static let sixOfPentacles = NSLocalizedString("six_of_pentacles", comment: "")
    public static let sevenOfPentacles = NSLocalizedString("seven_of_pentacles", comment: "")
    public static let eightOfPentacles = NSLocalizedString("eight_of_pentacles", comment: "")
    public static let nineOfPentacles = NSLocalizedString("nine_of_pentacles", comment: "")
    public static let tenOfPentacles = NSLocalizedString("ten_of_pentacles", comment: "")
    public static let pageOfPentacles = NSLocalizedString("page_of_pentacles", comment: "")
    public static let knightOfPentacles = NSLocalizedString("knight_of_pentacles", comment: "")
    public static let queenOfPentacles = NSLocalizedString("queen_of_pentacles", comment: "")
    public static let kingOfPentacles = NSLocalizedString("king_of_pentacles", comment: "")

    // Cups
    public static let aceOfCups = NSLocalizedString("ace_of_cups", comment: "")
    public static let twoOfCups = NSLocalizedString("two_of_cups", comment: "")
    public static let threeOfCups = NSLocalizedString("three_of_cups", comment: "")
    public static let fourOfCups = NSLocalizedString("four_of_cups", comment: "")
    public static let fiveOfCups = NSLocalizedString("five_of_cups", comment: "")
    public static let sixOfCups = NSLocalizedString("six_of_cups", comment: "")
    public static let sevenOfCups = NSLocalizedString("seven_of_cups", comment: "")
    public static let eightOfCups = NSLocalizedString("eight_of_cups", comment: "")
    public static let nineOfCups = NSLocalizedString("nine_of_cups", comment: "")
    public static let tenOfCups = NSLocalizedString("ten_of_cups", comment: "")
    public static let pageOfCups = NSLocalizedString("page_of_cups", comment: "")
    public static let knightOfCups = NSLocalizedString("knight_of_cups", comment: "")
    public static let queenOfCups = NSLocalizedString("queen_of_cups", comment: "")
    public static let kingOfCups = NSLocalizedString("king_of_cups", comment: "")

    // Swords
    public static let aceOfSwords = NSLocalizedString("ace_of_swords", comment: "")
    public static let twoOfSwords = NSLocalizedString("two_of_swords", comment: "")
    public static let threeOfSwords = NSLocalizedString("three_of_swords", comment: "")
    public static let fourOfSwords = NSLocalizedString("four_of_swords", comment: "")
    public static let fiveOfSwords = NSLocalizedString("five_of_swords", comment: "")
    public static let sixOfSwords = NSLocalizedString("six_of_swords", comment: "")
    public static let sevenOfSwords = NSLocalizedString("seven_of_swords", comment: "")
    public static let eightOfSwords = NSLocalizedString("eight_of_swords", comment: "")
    public static let nineOfSwords = NSLocalizedString("nine_of_swords", comment: "")
    public static let tenOfSwords = NSLocalizedString("ten_of_swords", comment: "")
    public static let pageOfSwords = NSLocalizedString("page_of_swords", comment: "")
    public static let knightOfSwords = NSLocalizedString("knight_of_swords", comment: "")
    public static let queenOfSwords = NSLocalizedString("queen_of_swords", comment: "")
    public static let kingOfSwords = NSLocalizedString("king_of_swords", comment: "")
    
    // MARK: - Neutral Keywords
    // - Major Arcana -
    public static let foolNeutral = NSLocalizedString("fool_neutral", comment: "")
    public static let magicianNeutral = NSLocalizedString("magician_neutral", comment: "")
    public static let highPriestessNeutral = NSLocalizedString("high_priestess_neutral", comment: "")
    public static let empressNeutral = NSLocalizedString("empress_neutral", comment: "")
    public static let emperorNeutral = NSLocalizedString("emperor_neutral", comment: "")
    public static let hierophantNeutral = NSLocalizedString("hierophant_neutral", comment: "")
    public static let loversNeutral = NSLocalizedString("lovers_neutral", comment: "")
    public static let chariotNeutral = NSLocalizedString("chariot_neutral", comment: "")
    public static let strengthNeutral = NSLocalizedString("strength_neutral", comment: "")
    public static let hermitNeutral = NSLocalizedString("hermit_neutral", comment: "")
    public static let wheelOfFortuneNeutral = NSLocalizedString("wheel_of_fortune_neutral", comment: "")
    public static let justiceNeutral = NSLocalizedString("justice_neutral", comment: "")
    public static let hangedManNeutral = NSLocalizedString("hanged_man_neutral", comment: "")
    public static let deathNeutral = NSLocalizedString("death_neutral", comment: "")
    public static let temperanceNeutral = NSLocalizedString("temperance_neutral", comment: "")
    public static let devilNeutral = NSLocalizedString("devil_neutral", comment: "")
    public static let towerNeutral = NSLocalizedString("tower_neutral", comment: "")
    public static let starNeutral = NSLocalizedString("star_neutral", comment: "")
    public static let moonNeutral = NSLocalizedString("moon_neutral", comment: "")
    public static let sunNeutral = NSLocalizedString("sun_neutral", comment: "")
    public static let judgementNeutral = NSLocalizedString("judgement_neutral", comment: "")
    public static let worldNeutral = NSLocalizedString("world_neutral", comment: "")

    // - Minor Arcana -
    // Wands
    public static let aceOfWandsNeutral = NSLocalizedString("ace_of_wands_neutral", comment: "")
    public static let twoOfWandsNeutral = NSLocalizedString("two_of_wands_neutral", comment: "")
    public static let threeOfWandsNeutral = NSLocalizedString("three_of_wands_neutral", comment: "")
    public static let fourOfWandsNeutral = NSLocalizedString("four_of_wands_neutral", comment: "")
    public static let fiveOfWandsNeutral = NSLocalizedString("five_of_wands_neutral", comment: "")
    public static let sixOfWandsNeutral = NSLocalizedString("six_of_wands_neutral", comment: "")
    public static let sevenOfWandsNeutral = NSLocalizedString("seven_of_wands_neutral", comment: "")
    public static let eightOfWandsNeutral = NSLocalizedString("eight_of_wands_neutral", comment: "")
    public static let nineOfWandsNeutral = NSLocalizedString("nine_of_wands_neutral", comment: "")
    public static let tenOfWandsNeutral = NSLocalizedString("ten_of_wands_neutral", comment: "")
    public static let pageOfWandsNeutral = NSLocalizedString("page_of_wands_neutral", comment: "")
    public static let knightOfWandsNeutral = NSLocalizedString("knight_of_wands_neutral", comment: "")
    public static let queenOfWandsNeutral = NSLocalizedString("queen_of_wands_neutral", comment: "")
    public static let kingOfWandsNeutral = NSLocalizedString("king_of_wands_neutral", comment: "")

    // Pentacles
    public static let aceOfPentaclesNeutral = NSLocalizedString("ace_of_pentacles_neutral", comment: "")
    public static let twoOfPentaclesNeutral = NSLocalizedString("two_of_pentacles_neutral", comment: "")
    public static let threeOfPentaclesNeutral = NSLocalizedString("three_of_pentacles_neutral", comment: "")
    public static let fourOfPentaclesNeutral = NSLocalizedString("four_of_pentacles_neutral", comment: "")
    public static let fiveOfPentaclesNeutral = NSLocalizedString("five_of_pentacles_neutral", comment: "")
    public static let sixOfPentaclesNeutral = NSLocalizedString("six_of_pentacles_neutral", comment: "")
    public static let sevenOfPentaclesNeutral = NSLocalizedString("seven_of_pentacles_neutral", comment: "")
    public static let eightOfPentaclesNeutral = NSLocalizedString("eight_of_pentacles_neutral", comment: "")
    public static let nineOfPentaclesNeutral = NSLocalizedString("nine_of_pentacles_neutral", comment: "")
    public static let tenOfPentaclesNeutral = NSLocalizedString("ten_of_pentacles_neutral", comment: "")
    public static let pageOfPentaclesNeutral = NSLocalizedString("page_of_pentacles_neutral", comment: "")
    public static let knightOfPentaclesNeutral = NSLocalizedString("knight_of_pentacles_neutral", comment: "")
    public static let queenOfPentaclesNeutral = NSLocalizedString("queen_of_pentacles_neutral", comment: "")
    public static let kingOfPentaclesNeutral = NSLocalizedString("king_of_pentacles_neutral", comment: "")

    // Cups
    public static let aceOfCupsNeutral = NSLocalizedString("ace_of_cups_neutral", comment: "")
    public static let twoOfCupsNeutral = NSLocalizedString("two_of_cups_neutral", comment: "")
    public static let threeOfCupsNeutral = NSLocalizedString("three_of_cups_neutral", comment: "")
    public static let fourOfCupsNeutral = NSLocalizedString("four_of_cups_neutral", comment: "")
    public static let fiveOfCupsNeutral = NSLocalizedString("five_of_cups_neutral", comment: "")
    public static let sixOfCupsNeutral = NSLocalizedString("six_of_cups_neutral", comment: "")
    public static let sevenOfCupsNeutral = NSLocalizedString("seven_of_cups_neutral", comment: "")
    public static let eightOfCupsNeutral = NSLocalizedString("eight_of_cups_neutral", comment: "")
    public static let nineOfCupsNeutral = NSLocalizedString("nine_of_cups_neutral", comment: "")
    public static let tenOfCupsNeutral = NSLocalizedString("ten_of_cups_neutral", comment: "")
    public static let pageOfCupsNeutral = NSLocalizedString("page_of_cups_neutral", comment: "")
    public static let knightOfCupsNeutral = NSLocalizedString("knight_of_cups_neutral", comment: "")
    public static let queenOfCupsNeutral = NSLocalizedString("queen_of_cups_neutral", comment: "")
    public static let kingOfCupsNeutral = NSLocalizedString("king_of_cups_neutral", comment: "")

    // Swords
    public static let aceOfSwordsNeutral = NSLocalizedString("ace_of_swords_neutral", comment: "")
    public static let twoOfSwordsNeutral = NSLocalizedString("two_of_swords_neutral", comment: "")
    public static let threeOfSwordsNeutral = NSLocalizedString("three_of_swords_neutral", comment: "")
    public static let fourOfSwordsNeutral = NSLocalizedString("four_of_swords_neutral", comment: "")
    public static let fiveOfSwordsNeutral = NSLocalizedString("five_of_swords_neutral", comment: "")
    public static let sixOfSwordsNeutral = NSLocalizedString("six_of_swords_neutral", comment: "")
    public static let sevenOfSwordsNeutral = NSLocalizedString("seven_of_swords_neutral", comment: "")
    public static let eightOfSwordsNeutral = NSLocalizedString("eight_of_swords_neutral", comment: "")
    public static let nineOfSwordsNeutral = NSLocalizedString("nine_of_swords_neutral", comment: "")
    public static let tenOfSwordsNeutral = NSLocalizedString("ten_of_swords_neutral", comment: "")
    public static let pageOfSwordsNeutral = NSLocalizedString("page_of_swords_neutral", comment: "")
    public static let knightOfSwordsNeutral = NSLocalizedString("knight_of_swords_neutral", comment: "")
    public static let queenOfSwordsNeutral = NSLocalizedString("queen_of_swords_neutral", comment: "")
    public static let kingOfSwordsNeutral = NSLocalizedString("king_of_swords_neutral", comment: "")
    
    // MARK: - Positive Keywords
    // - Major Arcana -
    public static let foolPositive = NSLocalizedString("fool_positive", comment: "")
    public static let magicianPositive = NSLocalizedString("magician_positive", comment: "")
    public static let highPriestessPositive = NSLocalizedString("high_priestess_positive", comment: "")
    public static let empressPositive = NSLocalizedString("empress_positive", comment: "")
    public static let emperorPositive = NSLocalizedString("emperor_positive", comment: "")
    public static let hierophantPositive = NSLocalizedString("hierophant_positive", comment: "")
    public static let loversPositive = NSLocalizedString("lovers_positive", comment: "")
    public static let chariotPositive = NSLocalizedString("chariot_positive", comment: "")
    public static let strengthPositive = NSLocalizedString("strength_positive", comment: "")
    public static let hermitPositive = NSLocalizedString("hermit_positive", comment: "")
    public static let wheelOfFortunePositive = NSLocalizedString("wheel_of_fortune_positive", comment: "")
    public static let justicePositive = NSLocalizedString("justice_positive", comment: "")
    public static let hangedManPositive = NSLocalizedString("hanged_man_positive", comment: "")
    public static let deathPositive = NSLocalizedString("death_positive", comment: "")
    public static let temperancePositive = NSLocalizedString("temperance_positive", comment: "")
    public static let devilPositive = NSLocalizedString("devil_positive", comment: "")
    public static let towerPositive = NSLocalizedString("tower_positive", comment: "")
    public static let starPositive = NSLocalizedString("star_positive", comment: "")
    public static let moonPositive = NSLocalizedString("moon_positive", comment: "")
    public static let sunPositive = NSLocalizedString("sun_positive", comment: "")
    public static let judgementPositive = NSLocalizedString("judgement_positive", comment: "")
    public static let worldPositive = NSLocalizedString("world_positive", comment: "")

    // - Minor Arcana -
    // Wands
    public static let aceOfWandsPositive = NSLocalizedString("ace_of_wands_positive", comment: "")
    public static let twoOfWandsPositive = NSLocalizedString("two_of_wands_positive", comment: "")
    public static let threeOfWandsPositive = NSLocalizedString("three_of_wands_positive", comment: "")
    public static let fourOfWandsPositive = NSLocalizedString("four_of_wands_positive", comment: "")
    public static let fiveOfWandsPositive = NSLocalizedString("five_of_wands_positive", comment: "")
    public static let sixOfWandsPositive = NSLocalizedString("six_of_wands_positive", comment: "")
    public static let sevenOfWandsPositive = NSLocalizedString("seven_of_wands_positive", comment: "")
    public static let eightOfWandsPositive = NSLocalizedString("eight_of_wands_positive", comment: "")
    public static let nineOfWandsPositive = NSLocalizedString("nine_of_wands_positive", comment: "")
    public static let tenOfWandsPositive = NSLocalizedString("ten_of_wands_positive", comment: "")
    public static let pageOfWandsPositive = NSLocalizedString("page_of_wands_positive", comment: "")
    public static let knightOfWandsPositive = NSLocalizedString("knight_of_wands_positive", comment: "")
    public static let queenOfWandsPositive = NSLocalizedString("queen_of_wands_positive", comment: "")
    public static let kingOfWandsPositive = NSLocalizedString("king_of_wands_positive", comment: "")

    // Pentacles
    public static let aceOfPentaclesPositive = NSLocalizedString("ace_of_pentacles_positive", comment: "")
    public static let twoOfPentaclesPositive = NSLocalizedString("two_of_pentacles_positive", comment: "")
    public static let threeOfPentaclesPositive = NSLocalizedString("three_of_pentacles_positive", comment: "")
    public static let fourOfPentaclesPositive = NSLocalizedString("four_of_pentacles_positive", comment: "")
    public static let fiveOfPentaclesPositive = NSLocalizedString("five_of_pentacles_positive", comment: "")
    public static let sixOfPentaclesPositive = NSLocalizedString("six_of_pentacles_positive", comment: "")
    public static let sevenOfPentaclesPositive = NSLocalizedString("seven_of_pentacles_positive", comment: "")
    public static let eightOfPentaclesPositive = NSLocalizedString("eight_of_pentacles_positive", comment: "")
    public static let nineOfPentaclesPositive = NSLocalizedString("nine_of_pentacles_positive", comment: "")
    public static let tenOfPentaclesPositive = NSLocalizedString("ten_of_pentacles_positive", comment: "")
    public static let pageOfPentaclesPositive = NSLocalizedString("page_of_pentacles_positive", comment: "")
    public static let knightOfPentaclesPositive = NSLocalizedString("knight_of_pentacles_positive", comment: "")
    public static let queenOfPentaclesPositive = NSLocalizedString("queen_of_pentacles_positive", comment: "")
    public static let kingOfPentaclesPositive = NSLocalizedString("king_of_pentacles_positive", comment: "")

    // Cups
    public static let aceOfCupsPositive = NSLocalizedString("ace_of_cups_positive", comment: "")
    public static let twoOfCupsPositive = NSLocalizedString("two_of_cups_positive", comment: "")
    public static let threeOfCupsPositive = NSLocalizedString("three_of_cups_positive", comment: "")
    public static let fourOfCupsPositive = NSLocalizedString("four_of_cups_positive", comment: "")
    public static let fiveOfCupsPositive = NSLocalizedString("five_of_cups_positive", comment: "")
    public static let sixOfCupsPositive = NSLocalizedString("six_of_cups_positive", comment: "")
    public static let sevenOfCupsPositive = NSLocalizedString("seven_of_cups_positive", comment: "")
    public static let eightOfCupsPositive = NSLocalizedString("eight_of_cups_positive", comment: "")
    public static let nineOfCupsPositive = NSLocalizedString("nine_of_cups_positive", comment: "")
    public static let tenOfCupsPositive = NSLocalizedString("ten_of_cups_positive", comment: "")
    public static let pageOfCupsPositive = NSLocalizedString("page_of_cups_positive", comment: "")
    public static let knightOfCupsPositive = NSLocalizedString("knight_of_cups_positive", comment: "")
    public static let queenOfCupsPositive = NSLocalizedString("queen_of_cups_positive", comment: "")
    public static let kingOfCupsPositive = NSLocalizedString("king_of_cups_positive", comment: "")

    // Swords
    public static let aceOfSwordsPositive = NSLocalizedString("ace_of_swords_positive", comment: "")
    public static let twoOfSwordsPositive = NSLocalizedString("two_of_swords_positive", comment: "")
    public static let threeOfSwordsPositive = NSLocalizedString("three_of_swords_positive", comment: "")
    public static let fourOfSwordsPositive = NSLocalizedString("four_of_swords_positive", comment: "")
    public static let fiveOfSwordsPositive = NSLocalizedString("five_of_swords_positive", comment: "")
    public static let sixOfSwordsPositive = NSLocalizedString("six_of_swords_positive", comment: "")
    public static let sevenOfSwordsPositive = NSLocalizedString("seven_of_swords_positive", comment: "")
    public static let eightOfSwordsPositive = NSLocalizedString("eight_of_swords_positive", comment: "")
    public static let nineOfSwordsPositive = NSLocalizedString("nine_of_swords_positive", comment: "")
    public static let tenOfSwordsPositive = NSLocalizedString("ten_of_swords_positive", comment: "")
    public static let pageOfSwordsPositive = NSLocalizedString("page_of_swords_positive", comment: "")
    public static let knightOfSwordsPositive = NSLocalizedString("knight_of_swords_positive", comment: "")
    public static let queenOfSwordsPositive = NSLocalizedString("queen_of_swords_positive", comment: "")
    public static let kingOfSwordsPositive = NSLocalizedString("king_of_swords_positive", comment: "")
    
    // MARK: - Negative Keywords
    // - Major Arcana -
    public static let foolNegative = NSLocalizedString("fool_negative", comment: "")
    public static let magicianNegative = NSLocalizedString("magician_negative", comment: "")
    public static let highPriestessNegative = NSLocalizedString("high_priestess_negative", comment: "")
    public static let empressNegative = NSLocalizedString("empress_negative", comment: "")
    public static let emperorNegative = NSLocalizedString("emperor_negative", comment: "")
    public static let hierophantNegative = NSLocalizedString("hierophant_negative", comment: "")
    public static let loversNegative = NSLocalizedString("lovers_negative", comment: "")
    public static let chariotNegative = NSLocalizedString("chariot_negative", comment: "")
    public static let strengthNegative = NSLocalizedString("strength_negative", comment: "")
    public static let hermitNegative = NSLocalizedString("hermit_negative", comment: "")
    public static let wheelOfFortuneNegative = NSLocalizedString("wheel_of_fortune_negative", comment: "")
    public static let justiceNegative = NSLocalizedString("justice_negative", comment: "")
    public static let hangedManNegative = NSLocalizedString("hanged_man_negative", comment: "")
    public static let deathNegative = NSLocalizedString("death_negative", comment: "")
    public static let temperanceNegative = NSLocalizedString("temperance_negative", comment: "")
    public static let devilNegative = NSLocalizedString("devil_negative", comment: "")
    public static let towerNegative = NSLocalizedString("tower_negative", comment: "")
    public static let starNegative = NSLocalizedString("star_negative", comment: "")
    public static let moonNegative = NSLocalizedString("moon_negative", comment: "")
    public static let sunNegative = NSLocalizedString("sun_negative", comment: "")
    public static let judgementNegative = NSLocalizedString("judgement_negative", comment: "")
    public static let worldNegative = NSLocalizedString("world_negative", comment: "")

    // - Minor Arcana -
    // Wands
    public static let aceOfWandsNegative = NSLocalizedString("ace_of_wands_negative", comment: "")
    public static let twoOfWandsNegative = NSLocalizedString("two_of_wands_negative", comment: "")
    public static let threeOfWandsNegative = NSLocalizedString("three_of_wands_negative", comment: "")
    public static let fourOfWandsNegative = NSLocalizedString("four_of_wands_negative", comment: "")
    public static let fiveOfWandsNegative = NSLocalizedString("five_of_wands_negative", comment: "")
    public static let sixOfWandsNegative = NSLocalizedString("six_of_wands_negative", comment: "")
    public static let sevenOfWandsNegative = NSLocalizedString("seven_of_wands_negative", comment: "")
    public static let eightOfWandsNegative = NSLocalizedString("eight_of_wands_negative", comment: "")
    public static let nineOfWandsNegative = NSLocalizedString("nine_of_wands_negative", comment: "")
    public static let tenOfWandsNegative = NSLocalizedString("ten_of_wands_negative", comment: "")
    public static let pageOfWandsNegative = NSLocalizedString("page_of_wands_negative", comment: "")
    public static let knightOfWandsNegative = NSLocalizedString("knight_of_wands_negative", comment: "")
    public static let queenOfWandsNegative = NSLocalizedString("queen_of_wands_negative", comment: "")
    public static let kingOfWandsNegative = NSLocalizedString("king_of_wands_negative", comment: "")

    // Pentacles
    public static let aceOfPentaclesNegative = NSLocalizedString("ace_of_pentacles_negative", comment: "")
    public static let twoOfPentaclesNegative = NSLocalizedString("two_of_pentacles_negative", comment: "")
    public static let threeOfPentaclesNegative = NSLocalizedString("three_of_pentacles_negative", comment: "")
    public static let fourOfPentaclesNegative = NSLocalizedString("four_of_pentacles_negative", comment: "")
    public static let fiveOfPentaclesNegative = NSLocalizedString("five_of_pentacles_negative", comment: "")
    public static let sixOfPentaclesNegative = NSLocalizedString("six_of_pentacles_negative", comment: "")
    public static let sevenOfPentaclesNegative = NSLocalizedString("seven_of_pentacles_negative", comment: "")
    public static let eightOfPentaclesNegative = NSLocalizedString("eight_of_pentacles_negative", comment: "")
    public static let nineOfPentaclesNegative = NSLocalizedString("nine_of_pentacles_negative", comment: "")
    public static let tenOfPentaclesNegative = NSLocalizedString("ten_of_pentacles_negative", comment: "")
    public static let pageOfPentaclesNegative = NSLocalizedString("page_of_pentacles_negative", comment: "")
    public static let knightOfPentaclesNegative = NSLocalizedString("knight_of_pentacles_negative", comment: "")
    public static let queenOfPentaclesNegative = NSLocalizedString("queen_of_pentacles_negative", comment: "")
    public static let kingOfPentaclesNegative = NSLocalizedString("king_of_pentacles_negative", comment: "")

    // Cups
    public static let aceOfCupsNegative = NSLocalizedString("ace_of_cups_negative", comment: "")
    public static let twoOfCupsNegative = NSLocalizedString("two_of_cups_negative", comment: "")
    public static let threeOfCupsNegative = NSLocalizedString("three_of_cups_negative", comment: "")
    public static let fourOfCupsNegative = NSLocalizedString("four_of_cups_negative", comment: "")
    public static let fiveOfCupsNegative = NSLocalizedString("five_of_cups_negative", comment: "")
    public static let sixOfCupsNegative = NSLocalizedString("six_of_cups_negative", comment: "")
    public static let sevenOfCupsNegative = NSLocalizedString("seven_of_cups_negative", comment: "")
    public static let eightOfCupsNegative = NSLocalizedString("eight_of_cups_negative", comment: "")
    public static let nineOfCupsNegative = NSLocalizedString("nine_of_cups_negative", comment: "")
    public static let tenOfCupsNegative = NSLocalizedString("ten_of_cups_negative", comment: "")
    public static let pageOfCupsNegative = NSLocalizedString("page_of_cups_negative", comment: "")
    public static let knightOfCupsNegative = NSLocalizedString("knight_of_cups_negative", comment: "")
    public static let queenOfCupsNegative = NSLocalizedString("queen_of_cups_negative", comment: "")
    public static let kingOfCupsNegative = NSLocalizedString("king_of_cups_negative", comment: "")

    // Swords
    public static let aceOfSwordsNegative = NSLocalizedString("ace_of_swords_negative", comment: "")
    public static let twoOfSwordsNegative = NSLocalizedString("two_of_swords_negative", comment: "")
    public static let threeOfSwordsNegative = NSLocalizedString("three_of_swords_negative", comment: "")
    public static let fourOfSwordsNegative = NSLocalizedString("four_of_swords_negative", comment: "")
    public static let fiveOfSwordsNegative = NSLocalizedString("five_of_swords_negative", comment: "")
    public static let sixOfSwordsNegative = NSLocalizedString("six_of_swords_negative", comment: "")
    public static let sevenOfSwordsNegative = NSLocalizedString("seven_of_swords_negative", comment: "")
    public static let eightOfSwordsNegative = NSLocalizedString("eight_of_swords_negative", comment: "")
    public static let nineOfSwordsNegative = NSLocalizedString("nine_of_swords_negative", comment: "")
    public static let tenOfSwordsNegative = NSLocalizedString("ten_of_swords_negative", comment: "")
    public static let pageOfSwordsNegative = NSLocalizedString("page_of_swords_negative", comment: "")
    public static let knightOfSwordsNegative = NSLocalizedString("knight_of_swords_negative", comment: "")
    public static let queenOfSwordsNegative = NSLocalizedString("queen_of_swords_negative", comment: "")
    public static let kingOfSwordsNegative = NSLocalizedString("king_of_swords_negative", comment: "")
}
